name: 'proto_loc_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'proto_loc'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Define project-level variables
vars:
  TAXI_ZONES_SHP_PATH: "/app/01_source_data/nyc_yellow_taxi_demo_data/taxi_zones/taxi_zones.shp"

models:
  proto_loc_dbt:
    # Applies to all files under models/.../
    materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
      dim_taxi_zones_geospatial:
        +enabled: true
