proto_loc:
  outputs:
    dev:
      type: duckdb
      path: '02_duck_db/02_dev/dev.duckdb'
      schema: 'main'
      threads: 1
      keepalives_idle: 0
      search_path: 'stg,mart'
    prod:
      type: duckdb
      path: '02_duck_db/03_prod/prod.duckdb'
      schema: 'main'
      threads: 1
      keepalives_idle: 0
      search_path: 'stg,mart'
  target: dev
